version: '3.8'

networks:
  my_network:
    driver: bridge

services:
  web:
    build: .
    networks:
      - my_network
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["/wait-for-it.sh", "db:5432", "--timeout=60", "--", "sh", "-c", "flask db upgrade && flask run --host=0.0.0.0"]

  db:
    image: postgres:13
    networks:
      - my_network
    environment:
      POSTGRES_DB: dev_hotel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: