version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key
      - DEV_DATABASE_URL=postgresql://root:root@db:5432/dev_hotel
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dev_hotel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: