version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env  # .envファイルから環境変数を読み込み
    environment:
      - FLASK_ENV=development
      - DEV_DATABASE_URL=${DEV_DATABASE_URL}  # .envファイルから読み込み
    working_dir: /app
    depends_on:
      - db
    entrypoint: ["/wait-for-it.sh", "db:5432", "--timeout=60", "--", "gunicorn", "-w 4 -b 0.0.0.0:5000 run:app"]
    # entrypoint: ["/wait-for-it.sh", "db:5432", "--timeout=60", "--", "sh", "-c", "flask db upgrade && flask run --host=0.0.0.0"]

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: dev_hotel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    driver: bridge